# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:28:11+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class Cls(Enum):
    labelComponent = 'labelComponent'
    numberComponent = 'numberComponent'
    textComponent = 'textComponent'
    imageComponent = 'imageComponent'
    dateComponent = 'dateComponent'
    hlineComponent = 'hlineComponent'
    vlineComponent = 'vlineComponent'
    tableComponent = 'tableComponent'
    compositeComponent = 'compositeComponent'
    barcodeComponent = 'barcodeComponent'
    qrcodeComponent = 'qrcodeComponent'
    chartComponent = 'chartComponent'
    rectangleComponent = 'rectangleComponent'
    headerComponent = 'headerComponent'
    footerComponent = 'footerComponent'
    checkboxComponent = 'checkboxComponent'
    radioComponent = 'radioComponent'


class Component(BaseModel):
    cls: Optional[Cls] = Field(
        None, description='Defines component class/type', examples=['labelComponent']
    )
    dataIndex: Optional[str] = Field(
        None,
        description='Defines data field for Table and Container components which are used to iterate over list of items',
        examples=['line_items'],
    )
    height: Optional[float] = Field(None, description='Height in units', examples=[1])
    id: Optional[str] = Field(
        None, description='Component id', examples=['component-12313']
    )
    left: Optional[float] = Field(
        None, description='Position from the page left in units', examples=[2.5]
    )
    top: Optional[float] = Field(
        None, description='Position from the page top in units', examples=[4.2]
    )
    value: Optional[str] = Field(
        None, description='Component value', examples=['${price}']
    )
    width: Optional[float] = Field(None, description='Width in units', examples=[3.5])
    zindex: Optional[int] = Field(
        None,
        description='Defines the rendering order on page. Components with smaller zindex are rendered before',
        examples=[102],
    )


class Data(BaseModel):
    id: Optional[int] = Field(None, examples=[12312])
    name: Optional[str] = Field(None, examples=['Sample Data'])


class Template(BaseModel):
    id: Optional[int] = Field(None, description='Unique identifier', examples=[24382])
    modified: Optional[str] = Field(
        None,
        description='Timestamp when the template was modified',
        examples=['2017-10-21 11:49:28'],
    )
    name: Optional[str] = Field(
        None, description='Template name', examples=['Invoice template']
    )
    owner: Optional[bool] = Field(
        None,
        description='Indicates if the workspace is the owner of the template',
        examples=[True],
    )
    tags: Optional[List[str]] = Field(
        None,
        description='A list of tags assigned to a template',
        examples=[['invoice', 'orders']],
    )


class DataSettings(BaseModel):
    filterBy: Optional[List[Dict[str, Any]]] = None
    sortBy: Optional[List[Dict[str, Any]]] = None


class Editor(BaseModel):
    heightMultiplier: Optional[float] = Field(None, examples=[2])


class Format(Enum):
    A4 = 'A4'
    letter = 'letter'
    custom = 'custom'


class Margins(BaseModel):
    bottom: Optional[float] = Field(None, examples=[0.5])
    left: Optional[float] = Field(None, examples=[0.5])
    right: Optional[float] = Field(None, examples=[0.5])
    top: Optional[float] = Field(None, examples=[0.5])


class Orientation(Enum):
    portrait = 'portrait'
    landscape = 'landscape'


class RepeatLayout(BaseModel):
    format: Optional[Format] = Field(
        None, description='Defines template page size', examples=['A4']
    )
    height: Optional[float] = Field(
        None, description='Page height in units', examples=[29.7]
    )
    width: Optional[float] = Field(
        None, description='Page width in units', examples=[21]
    )


class Rotation(Enum):
    integer_0 = 0
    integer_90 = 90
    integer_180 = 180
    integer_270 = 270


class Unit(Enum):
    cm = 'cm'
    in_ = 'in'


class Layout(BaseModel):
    emptyLabels: Optional[int] = Field(
        None,
        description='Defines how many pages or labels should be empty',
        examples=[0],
    )
    format: Optional[Format] = Field(
        None, description='Defines template page size', examples=['A4']
    )
    height: Optional[float] = Field(
        None, description='Page height in units', examples=[29.7]
    )
    margins: Optional[Margins] = Field(None, description='Page margins in units')
    orientation: Optional[Orientation] = Field(
        None, description='Page orientation', examples=['portrait']
    )
    repeatLayout: Optional[RepeatLayout] = Field(
        None,
        description='Defines page size if layout is repeated on the page e.g sheet labels',
    )
    rotation: Optional[Rotation] = Field(
        None, description='Page rotation in degrees', examples=[0]
    )
    unit: Optional[Unit] = Field(None, description='Measure unit', examples=['cm'])
    width: Optional[float] = Field(
        None, description='Page width in units', examples=[21]
    )


class Margins1(BaseModel):
    bottom: Optional[float] = Field(
        None, description='Page or label margin from bottom', examples=[0.5]
    )
    right: Optional[float] = Field(
        None, description='Page or label margin from right', examples=[0.5]
    )


class Page(BaseModel):
    components: Optional[List[Component]] = None
    height: Optional[float] = Field(
        None, description='Page height in units', examples=[29.7]
    )
    margins: Optional[Margins1] = None
    width: Optional[float] = Field(
        None, description='Page width in units', examples=[21]
    )


class TemplateDefinition(BaseModel):
    dataSettings: Optional[DataSettings] = Field(
        None, description='Defines filter and sort option for root data set.'
    )
    editor: Optional[Editor] = Field(
        None, description='Configuration preferences for the editor'
    )
    id: Optional[int] = Field(None, description='Unique identifier', examples=[24382])
    isDraft: Optional[bool] = Field(
        None,
        description='Indicates if the template is a draft or published.',
        examples=[True],
    )
    layout: Optional[Layout] = Field(
        None, description='Defines template layout (e.g page format, margins).'
    )
    name: Optional[str] = Field(
        None, description='Template name', examples=['Invoice template']
    )
    pages: Optional[List[Page]] = Field(
        None,
        description='Defines page or label size, margins and components on page or label',
    )
    tags: Optional[List[str]] = Field(
        None,
        description='A list of tags assigned to a template',
        examples=[['invoice', 'orders']],
    )


class Margins2(BaseModel):
    bottom: Optional[float] = Field(None, examples=[0.5])
    left: Optional[float] = Field(None, examples=[0.5])
    right: Optional[float] = Field(None, examples=[0.5])
    top: Optional[float] = Field(None, examples=[0.5])


class RepeatLayout1(BaseModel):
    format: Optional[Format] = Field(
        None, description='Defines template page size', examples=['A4']
    )
    height: Optional[float] = Field(
        None, description='Page height in units', examples=[29.7]
    )
    width: Optional[float] = Field(
        None, description='Page width in units', examples=[21]
    )


class Rotaion(Enum):
    integer_0 = 0
    integer_90 = 90
    integer_180 = 180
    integer_270 = 270


class Layout1(BaseModel):
    emptyLabels: Optional[int] = Field(
        None,
        description='Defines how many pages or labels should be empty',
        examples=[0],
    )
    format: Optional[Format] = Field(
        None, description='Defines template page size', examples=['A4']
    )
    height: Optional[float] = Field(
        None, description='Page height in units', examples=[29.7]
    )
    margins: Optional[Margins2] = Field(None, description='Page margins in units')
    orientation: Optional[Orientation] = Field(
        None, description='Page orientation', examples=['portrait']
    )
    repeatLayout: Optional[RepeatLayout1] = Field(
        None,
        description='Defines page size if layout is repeated on the page e.g sheet labels',
    )
    rotaion: Optional[Rotaion] = Field(
        None, description='Page rotation in degrees', examples=[0]
    )
    unit: Optional[Unit] = Field(None, description='Measure unit', examples=['cm'])
    width: Optional[float] = Field(
        None, description='Page width in units', examples=[21]
    )


class Margins3(BaseModel):
    bottom: Optional[float] = Field(
        None, description='Page or label margin from bottom', examples=[0.5]
    )
    right: Optional[float] = Field(
        None, description='Page or label margin from right', examples=[0.5]
    )


class Page1(BaseModel):
    components: Optional[List[Component]] = None
    height: Optional[float] = Field(
        None, description='Page height in units', examples=[29.7]
    )
    margins: Optional[Margins3] = None
    width: Optional[float] = Field(
        None, description='Page width in units', examples=[21]
    )


class TemplateDefinitionNew(BaseModel):
    isDraft: Optional[bool] = Field(
        None,
        description='Indicates if the template is a draft or published.',
        examples=[True],
    )
    layout: Optional[Layout1] = Field(
        None, description='Defines template layout (e.g page format, margins).'
    )
    name: str = Field(..., description='Template name', examples=['Invoice template'])
    pages: Optional[List[Page1]] = Field(
        None,
        description='Defines page or label size, margins and components on page or label',
    )
    tags: Optional[List[str]] = Field(
        None,
        description='A list of tags assigned to a template',
        examples=[['invoice', 'orders']],
    )


class Workspace(BaseModel):
    created_at: Optional[str] = Field(None, examples=['2020-04-01 12:03:12'])
    id: Optional[int] = Field(None, description='Internal workspace id', examples=[1])
    identifier: Optional[str] = Field(
        None,
        description='The unique workspace idenfitifer specified by your application',
        examples=['demo.example@actualreports.com'],
    )
    is_master_workspace: Optional[bool] = Field(
        None, description='True if a master workspace', examples=[False]
    )


class TemplatesGetResponse(BaseModel):
    response: Optional[List[Template]] = None


class Error(Enum):
    Authentication_failed__request_expired = 'Authentication failed: request expired'
    Authentication_failed__signature_or_secret_missing = (
        'Authentication failed: signature or secret missing'
    )
    Authentication_failed__workspace_missing = (
        'Authentication failed: workspace missing'
    )
    Authentication_failed__key_missing = 'Authentication failed: key missing'
    Authentication_failed__property__iss___issuer__missing_in_JWT = (
        'Authentication failed: property \'iss\' (issuer) missing in JWT'
    )
    Authentication_failed__property__sub___subject__missing_in_JWT = (
        'Authentication failed: property \'sub\' (subject) missing in JWT'
    )
    Authentication_failed__property__exp___expiration_time__missing_in_JWT = (
        'Authentication failed: property \'exp\' (expiration time) missing in JWT'
    )
    Authentication_failed__invalid__iss___issuer_ = (
        'Authentication failed: invalid \'iss\' (issuer)'
    )
    Authentication_failed__incorrect_signature = (
        'Authentication failed: incorrect signature'
    )
    Authentication_failed = 'Authentication failed'


class TemplatesGetResponse1(BaseModel):
    error: Optional[Error] = Field(
        None, description='Error description', examples=['Authentication failed']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[401])


class Error1(Enum):
    Your_account_has_exceeded_the_monthly_document_generation_limit_ = (
        'Your account has exceeded the monthly document generation limit.'
    )


class TemplatesGetResponse2(BaseModel):
    error: Optional[Error1] = Field(
        None, description='Error description', examples=['Access not granted']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[403])


class Error2(Enum):
    Entity_not_found = 'Entity not found'
    Resource_not_found = 'Resource not found'
    None_of_the_templates_is_available_for_the_workspace_ = (
        'None of the templates is available for the workspace.'
    )


class TemplatesGetResponse3(BaseModel):
    error: Optional[Error2] = Field(
        None, description='Error description', examples=['Entity not found']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[404])


class Error3(Enum):
    Unable_to_parse_JSON__please_check_formatting = (
        'Unable to parse JSON, please check formatting'
    )
    Required_parameter_missing = 'Required parameter missing'
    Required_parameter_missing__template_definition_not_defined = (
        'Required parameter missing: template definition not defined'
    )
    Required_parameter_missing__template_not_defined = (
        'Required parameter missing: template not defined'
    )


class TemplatesGetResponse4(BaseModel):
    error: Optional[Error3] = Field(
        None, description='Error description', examples=['Incorrect parameter value']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[422])


class TemplatesGetResponse5(BaseModel):
    error: Optional[str] = Field(
        None, description='Error description', examples=['Internal error']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[500])


class TemplatesPostResponse(BaseModel):
    response: Optional[TemplateDefinition] = None


class Error4(Enum):
    Authentication_failed__request_expired = 'Authentication failed: request expired'
    Authentication_failed__signature_or_secret_missing = (
        'Authentication failed: signature or secret missing'
    )
    Authentication_failed__workspace_missing = (
        'Authentication failed: workspace missing'
    )
    Authentication_failed__key_missing = 'Authentication failed: key missing'
    Authentication_failed__property__iss___issuer__missing_in_JWT = (
        'Authentication failed: property \'iss\' (issuer) missing in JWT'
    )
    Authentication_failed__property__sub___subject__missing_in_JWT = (
        'Authentication failed: property \'sub\' (subject) missing in JWT'
    )
    Authentication_failed__property__exp___expiration_time__missing_in_JWT = (
        'Authentication failed: property \'exp\' (expiration time) missing in JWT'
    )
    Authentication_failed__invalid__iss___issuer_ = (
        'Authentication failed: invalid \'iss\' (issuer)'
    )
    Authentication_failed__incorrect_signature = (
        'Authentication failed: incorrect signature'
    )
    Authentication_failed = 'Authentication failed'


class TemplatesPostResponse1(BaseModel):
    error: Optional[Error4] = Field(
        None, description='Error description', examples=['Authentication failed']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[401])


class Error5(Enum):
    Your_account_has_exceeded_the_monthly_document_generation_limit_ = (
        'Your account has exceeded the monthly document generation limit.'
    )


class TemplatesPostResponse2(BaseModel):
    error: Optional[Error5] = Field(
        None, description='Error description', examples=['Access not granted']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[403])


class Error6(Enum):
    Entity_not_found = 'Entity not found'
    Resource_not_found = 'Resource not found'
    None_of_the_templates_is_available_for_the_workspace_ = (
        'None of the templates is available for the workspace.'
    )


class TemplatesPostResponse3(BaseModel):
    error: Optional[Error6] = Field(
        None, description='Error description', examples=['Entity not found']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[404])


class Error7(Enum):
    Unable_to_parse_JSON__please_check_formatting = (
        'Unable to parse JSON, please check formatting'
    )
    Required_parameter_missing = 'Required parameter missing'
    Required_parameter_missing__template_definition_not_defined = (
        'Required parameter missing: template definition not defined'
    )
    Required_parameter_missing__template_not_defined = (
        'Required parameter missing: template not defined'
    )


class TemplatesPostResponse4(BaseModel):
    error: Optional[Error7] = Field(
        None, description='Error description', examples=['Incorrect parameter value']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[422])


class TemplatesPostResponse5(BaseModel):
    error: Optional[str] = Field(
        None, description='Error description', examples=['Internal error']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[500])


class Format4(Enum):
    pdf = 'pdf'
    html = 'html'
    zip = 'zip'
    xlsx = 'xlsx'


class Output(Enum):
    base64 = 'base64'
    url = 'url'
    I = 'I'


class Meta(BaseModel):
    content_type: Optional[str] = Field(
        None,
        alias='content-type',
        description='Document content type.',
        examples=['application/pdf'],
    )
    display_name: Optional[str] = Field(
        None,
        description='Document name without the file extension.',
        examples=['a2bd25b8921f3dc7a440fd7f427f90a4'],
    )
    encoding: Optional[str] = Field(
        None, description='Document encoding', examples=['base64']
    )
    name: Optional[str] = Field(
        None,
        description='Document name. This value is automatically generated if name attribute is not defined in request.',
        examples=['a2bd25b8921f3dc7a440fd7f427f90a4.pdf'],
    )


class TemplatesOutputPostResponse(BaseModel):
    meta: Optional[Meta] = None
    response: Optional[str] = Field(
        None,
        description='Base64 encoded document if the output=base64 is used or URL to the document when the output=url is used.',
        examples=['JVBERi0xLjcKJeLjz9MKNyAwIG9iago8PCAvVHlwZSA...'],
    )


class Error8(Enum):
    Authentication_failed__request_expired = 'Authentication failed: request expired'
    Authentication_failed__signature_or_secret_missing = (
        'Authentication failed: signature or secret missing'
    )
    Authentication_failed__workspace_missing = (
        'Authentication failed: workspace missing'
    )
    Authentication_failed__key_missing = 'Authentication failed: key missing'
    Authentication_failed__property__iss___issuer__missing_in_JWT = (
        'Authentication failed: property \'iss\' (issuer) missing in JWT'
    )
    Authentication_failed__property__sub___subject__missing_in_JWT = (
        'Authentication failed: property \'sub\' (subject) missing in JWT'
    )
    Authentication_failed__property__exp___expiration_time__missing_in_JWT = (
        'Authentication failed: property \'exp\' (expiration time) missing in JWT'
    )
    Authentication_failed__invalid__iss___issuer_ = (
        'Authentication failed: invalid \'iss\' (issuer)'
    )
    Authentication_failed__incorrect_signature = (
        'Authentication failed: incorrect signature'
    )
    Authentication_failed = 'Authentication failed'


class TemplatesOutputPostResponse1(BaseModel):
    error: Optional[Error8] = Field(
        None, description='Error description', examples=['Authentication failed']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[401])


class Error9(Enum):
    Your_account_has_exceeded_the_monthly_document_generation_limit_ = (
        'Your account has exceeded the monthly document generation limit.'
    )


class TemplatesOutputPostResponse2(BaseModel):
    error: Optional[Error9] = Field(
        None, description='Error description', examples=['Access not granted']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[403])


class Error10(Enum):
    Entity_not_found = 'Entity not found'
    Resource_not_found = 'Resource not found'
    None_of_the_templates_is_available_for_the_workspace_ = (
        'None of the templates is available for the workspace.'
    )


class TemplatesOutputPostResponse3(BaseModel):
    error: Optional[Error10] = Field(
        None, description='Error description', examples=['Entity not found']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[404])


class Error11(Enum):
    Unable_to_parse_JSON__please_check_formatting = (
        'Unable to parse JSON, please check formatting'
    )
    Required_parameter_missing = 'Required parameter missing'
    Required_parameter_missing__template_definition_not_defined = (
        'Required parameter missing: template definition not defined'
    )
    Required_parameter_missing__template_not_defined = (
        'Required parameter missing: template not defined'
    )


class TemplatesOutputPostResponse4(BaseModel):
    error: Optional[Error11] = Field(
        None, description='Error description', examples=['Incorrect parameter value']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[422])


class TemplatesOutputPostResponse5(BaseModel):
    error: Optional[str] = Field(
        None, description='Error description', examples=['Internal error']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[500])


class Response(BaseModel):
    success: Optional[bool] = Field(None, examples=[True])


class TemplatesTemplateIdDeleteResponse(BaseModel):
    response: Optional[Response] = None


class Error12(Enum):
    Authentication_failed__request_expired = 'Authentication failed: request expired'
    Authentication_failed__signature_or_secret_missing = (
        'Authentication failed: signature or secret missing'
    )
    Authentication_failed__workspace_missing = (
        'Authentication failed: workspace missing'
    )
    Authentication_failed__key_missing = 'Authentication failed: key missing'
    Authentication_failed__property__iss___issuer__missing_in_JWT = (
        'Authentication failed: property \'iss\' (issuer) missing in JWT'
    )
    Authentication_failed__property__sub___subject__missing_in_JWT = (
        'Authentication failed: property \'sub\' (subject) missing in JWT'
    )
    Authentication_failed__property__exp___expiration_time__missing_in_JWT = (
        'Authentication failed: property \'exp\' (expiration time) missing in JWT'
    )
    Authentication_failed__invalid__iss___issuer_ = (
        'Authentication failed: invalid \'iss\' (issuer)'
    )
    Authentication_failed__incorrect_signature = (
        'Authentication failed: incorrect signature'
    )
    Authentication_failed = 'Authentication failed'


class TemplatesTemplateIdDeleteResponse1(BaseModel):
    error: Optional[Error12] = Field(
        None, description='Error description', examples=['Authentication failed']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[401])


class Error13(Enum):
    Your_account_has_exceeded_the_monthly_document_generation_limit_ = (
        'Your account has exceeded the monthly document generation limit.'
    )


class TemplatesTemplateIdDeleteResponse2(BaseModel):
    error: Optional[Error13] = Field(
        None, description='Error description', examples=['Access not granted']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[403])


class Error14(Enum):
    Entity_not_found = 'Entity not found'
    Resource_not_found = 'Resource not found'
    None_of_the_templates_is_available_for_the_workspace_ = (
        'None of the templates is available for the workspace.'
    )


class TemplatesTemplateIdDeleteResponse3(BaseModel):
    error: Optional[Error14] = Field(
        None, description='Error description', examples=['Entity not found']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[404])


class Error15(Enum):
    Unable_to_parse_JSON__please_check_formatting = (
        'Unable to parse JSON, please check formatting'
    )
    Required_parameter_missing = 'Required parameter missing'
    Required_parameter_missing__template_definition_not_defined = (
        'Required parameter missing: template definition not defined'
    )
    Required_parameter_missing__template_not_defined = (
        'Required parameter missing: template not defined'
    )


class TemplatesTemplateIdDeleteResponse4(BaseModel):
    error: Optional[Error15] = Field(
        None, description='Error description', examples=['Incorrect parameter value']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[422])


class TemplatesTemplateIdDeleteResponse5(BaseModel):
    error: Optional[str] = Field(
        None, description='Error description', examples=['Internal error']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[500])


class TemplatesTemplateIdGetResponse(BaseModel):
    response: Optional[TemplateDefinition] = None


class Error16(Enum):
    Authentication_failed__request_expired = 'Authentication failed: request expired'
    Authentication_failed__signature_or_secret_missing = (
        'Authentication failed: signature or secret missing'
    )
    Authentication_failed__workspace_missing = (
        'Authentication failed: workspace missing'
    )
    Authentication_failed__key_missing = 'Authentication failed: key missing'
    Authentication_failed__property__iss___issuer__missing_in_JWT = (
        'Authentication failed: property \'iss\' (issuer) missing in JWT'
    )
    Authentication_failed__property__sub___subject__missing_in_JWT = (
        'Authentication failed: property \'sub\' (subject) missing in JWT'
    )
    Authentication_failed__property__exp___expiration_time__missing_in_JWT = (
        'Authentication failed: property \'exp\' (expiration time) missing in JWT'
    )
    Authentication_failed__invalid__iss___issuer_ = (
        'Authentication failed: invalid \'iss\' (issuer)'
    )
    Authentication_failed__incorrect_signature = (
        'Authentication failed: incorrect signature'
    )
    Authentication_failed = 'Authentication failed'


class TemplatesTemplateIdGetResponse1(BaseModel):
    error: Optional[Error16] = Field(
        None, description='Error description', examples=['Authentication failed']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[401])


class Error17(Enum):
    Your_account_has_exceeded_the_monthly_document_generation_limit_ = (
        'Your account has exceeded the monthly document generation limit.'
    )


class TemplatesTemplateIdGetResponse2(BaseModel):
    error: Optional[Error17] = Field(
        None, description='Error description', examples=['Access not granted']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[403])


class Error18(Enum):
    Entity_not_found = 'Entity not found'
    Resource_not_found = 'Resource not found'
    None_of_the_templates_is_available_for_the_workspace_ = (
        'None of the templates is available for the workspace.'
    )


class TemplatesTemplateIdGetResponse3(BaseModel):
    error: Optional[Error18] = Field(
        None, description='Error description', examples=['Entity not found']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[404])


class Error19(Enum):
    Unable_to_parse_JSON__please_check_formatting = (
        'Unable to parse JSON, please check formatting'
    )
    Required_parameter_missing = 'Required parameter missing'
    Required_parameter_missing__template_definition_not_defined = (
        'Required parameter missing: template definition not defined'
    )
    Required_parameter_missing__template_not_defined = (
        'Required parameter missing: template not defined'
    )


class TemplatesTemplateIdGetResponse4(BaseModel):
    error: Optional[Error19] = Field(
        None, description='Error description', examples=['Incorrect parameter value']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[422])


class TemplatesTemplateIdGetResponse5(BaseModel):
    error: Optional[str] = Field(
        None, description='Error description', examples=['Internal error']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[500])


class TemplatesTemplateIdPutResponse(BaseModel):
    response: Optional[TemplateDefinition] = None


class Error20(Enum):
    Authentication_failed__request_expired = 'Authentication failed: request expired'
    Authentication_failed__signature_or_secret_missing = (
        'Authentication failed: signature or secret missing'
    )
    Authentication_failed__workspace_missing = (
        'Authentication failed: workspace missing'
    )
    Authentication_failed__key_missing = 'Authentication failed: key missing'
    Authentication_failed__property__iss___issuer__missing_in_JWT = (
        'Authentication failed: property \'iss\' (issuer) missing in JWT'
    )
    Authentication_failed__property__sub___subject__missing_in_JWT = (
        'Authentication failed: property \'sub\' (subject) missing in JWT'
    )
    Authentication_failed__property__exp___expiration_time__missing_in_JWT = (
        'Authentication failed: property \'exp\' (expiration time) missing in JWT'
    )
    Authentication_failed__invalid__iss___issuer_ = (
        'Authentication failed: invalid \'iss\' (issuer)'
    )
    Authentication_failed__incorrect_signature = (
        'Authentication failed: incorrect signature'
    )
    Authentication_failed = 'Authentication failed'


class TemplatesTemplateIdPutResponse1(BaseModel):
    error: Optional[Error20] = Field(
        None, description='Error description', examples=['Authentication failed']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[401])


class Error21(Enum):
    Your_account_has_exceeded_the_monthly_document_generation_limit_ = (
        'Your account has exceeded the monthly document generation limit.'
    )


class TemplatesTemplateIdPutResponse2(BaseModel):
    error: Optional[Error21] = Field(
        None, description='Error description', examples=['Access not granted']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[403])


class Error22(Enum):
    Entity_not_found = 'Entity not found'
    Resource_not_found = 'Resource not found'
    None_of_the_templates_is_available_for_the_workspace_ = (
        'None of the templates is available for the workspace.'
    )


class TemplatesTemplateIdPutResponse3(BaseModel):
    error: Optional[Error22] = Field(
        None, description='Error description', examples=['Entity not found']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[404])


class Error23(Enum):
    Unable_to_parse_JSON__please_check_formatting = (
        'Unable to parse JSON, please check formatting'
    )
    Required_parameter_missing = 'Required parameter missing'
    Required_parameter_missing__template_definition_not_defined = (
        'Required parameter missing: template definition not defined'
    )
    Required_parameter_missing__template_not_defined = (
        'Required parameter missing: template not defined'
    )


class TemplatesTemplateIdPutResponse4(BaseModel):
    error: Optional[Error23] = Field(
        None, description='Error description', examples=['Incorrect parameter value']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[422])


class TemplatesTemplateIdPutResponse5(BaseModel):
    error: Optional[str] = Field(
        None, description='Error description', examples=['Internal error']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[500])


class TemplatesTemplateIdCopyPostResponse(BaseModel):
    response: Optional[TemplateDefinition] = None


class Error24(Enum):
    Authentication_failed__request_expired = 'Authentication failed: request expired'
    Authentication_failed__signature_or_secret_missing = (
        'Authentication failed: signature or secret missing'
    )
    Authentication_failed__workspace_missing = (
        'Authentication failed: workspace missing'
    )
    Authentication_failed__key_missing = 'Authentication failed: key missing'
    Authentication_failed__property__iss___issuer__missing_in_JWT = (
        'Authentication failed: property \'iss\' (issuer) missing in JWT'
    )
    Authentication_failed__property__sub___subject__missing_in_JWT = (
        'Authentication failed: property \'sub\' (subject) missing in JWT'
    )
    Authentication_failed__property__exp___expiration_time__missing_in_JWT = (
        'Authentication failed: property \'exp\' (expiration time) missing in JWT'
    )
    Authentication_failed__invalid__iss___issuer_ = (
        'Authentication failed: invalid \'iss\' (issuer)'
    )
    Authentication_failed__incorrect_signature = (
        'Authentication failed: incorrect signature'
    )
    Authentication_failed = 'Authentication failed'


class TemplatesTemplateIdCopyPostResponse1(BaseModel):
    error: Optional[Error24] = Field(
        None, description='Error description', examples=['Authentication failed']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[401])


class Error25(Enum):
    Your_account_has_exceeded_the_monthly_document_generation_limit_ = (
        'Your account has exceeded the monthly document generation limit.'
    )


class TemplatesTemplateIdCopyPostResponse2(BaseModel):
    error: Optional[Error25] = Field(
        None, description='Error description', examples=['Access not granted']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[403])


class Error26(Enum):
    Entity_not_found = 'Entity not found'
    Resource_not_found = 'Resource not found'
    None_of_the_templates_is_available_for_the_workspace_ = (
        'None of the templates is available for the workspace.'
    )


class TemplatesTemplateIdCopyPostResponse3(BaseModel):
    error: Optional[Error26] = Field(
        None, description='Error description', examples=['Entity not found']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[404])


class Error27(Enum):
    Unable_to_parse_JSON__please_check_formatting = (
        'Unable to parse JSON, please check formatting'
    )
    Required_parameter_missing = 'Required parameter missing'
    Required_parameter_missing__template_definition_not_defined = (
        'Required parameter missing: template definition not defined'
    )
    Required_parameter_missing__template_not_defined = (
        'Required parameter missing: template not defined'
    )


class TemplatesTemplateIdCopyPostResponse4(BaseModel):
    error: Optional[Error27] = Field(
        None, description='Error description', examples=['Incorrect parameter value']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[422])


class TemplatesTemplateIdCopyPostResponse5(BaseModel):
    error: Optional[str] = Field(
        None, description='Error description', examples=['Internal error']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[500])


class Language(Enum):
    en = 'en'
    et = 'et'
    cs = 'cs'
    sk = 'sk'
    ru = 'ru'


class TemplatesTemplateIdEditorPostRequest(BaseModel):
    pass


class TemplatesTemplateIdEditorPostResponse(BaseModel):
    response: Optional[str] = Field(
        None,
        examples=[
            'https://us1.pdfgeneratorapi.com/editor/open/2ff98760d39456c4b2cf974fef005ecf'
        ],
    )


class Error28(Enum):
    Authentication_failed__request_expired = 'Authentication failed: request expired'
    Authentication_failed__signature_or_secret_missing = (
        'Authentication failed: signature or secret missing'
    )
    Authentication_failed__workspace_missing = (
        'Authentication failed: workspace missing'
    )
    Authentication_failed__key_missing = 'Authentication failed: key missing'
    Authentication_failed__property__iss___issuer__missing_in_JWT = (
        'Authentication failed: property \'iss\' (issuer) missing in JWT'
    )
    Authentication_failed__property__sub___subject__missing_in_JWT = (
        'Authentication failed: property \'sub\' (subject) missing in JWT'
    )
    Authentication_failed__property__exp___expiration_time__missing_in_JWT = (
        'Authentication failed: property \'exp\' (expiration time) missing in JWT'
    )
    Authentication_failed__invalid__iss___issuer_ = (
        'Authentication failed: invalid \'iss\' (issuer)'
    )
    Authentication_failed__incorrect_signature = (
        'Authentication failed: incorrect signature'
    )
    Authentication_failed = 'Authentication failed'


class TemplatesTemplateIdEditorPostResponse1(BaseModel):
    error: Optional[Error28] = Field(
        None, description='Error description', examples=['Authentication failed']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[401])


class Error29(Enum):
    Your_account_has_exceeded_the_monthly_document_generation_limit_ = (
        'Your account has exceeded the monthly document generation limit.'
    )


class TemplatesTemplateIdEditorPostResponse2(BaseModel):
    error: Optional[Error29] = Field(
        None, description='Error description', examples=['Access not granted']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[403])


class Error30(Enum):
    Entity_not_found = 'Entity not found'
    Resource_not_found = 'Resource not found'
    None_of_the_templates_is_available_for_the_workspace_ = (
        'None of the templates is available for the workspace.'
    )


class TemplatesTemplateIdEditorPostResponse3(BaseModel):
    error: Optional[Error30] = Field(
        None, description='Error description', examples=['Entity not found']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[404])


class Error31(Enum):
    Unable_to_parse_JSON__please_check_formatting = (
        'Unable to parse JSON, please check formatting'
    )
    Required_parameter_missing = 'Required parameter missing'
    Required_parameter_missing__template_definition_not_defined = (
        'Required parameter missing: template definition not defined'
    )
    Required_parameter_missing__template_not_defined = (
        'Required parameter missing: template not defined'
    )


class TemplatesTemplateIdEditorPostResponse4(BaseModel):
    error: Optional[Error31] = Field(
        None, description='Error description', examples=['Incorrect parameter value']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[422])


class TemplatesTemplateIdEditorPostResponse5(BaseModel):
    error: Optional[str] = Field(
        None, description='Error description', examples=['Internal error']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[500])


class TemplatesTemplateIdOutputPostResponse(BaseModel):
    meta: Optional[Meta] = None
    response: Optional[str] = Field(
        None,
        description='Base64 encoded document if the output=base64 is used or URL to the document when the output=url is used.',
        examples=['JVBERi0xLjcKJeLjz9MKNyAwIG9iago8PCAvVHlwZSA...'],
    )


class Error32(Enum):
    Authentication_failed__request_expired = 'Authentication failed: request expired'
    Authentication_failed__signature_or_secret_missing = (
        'Authentication failed: signature or secret missing'
    )
    Authentication_failed__workspace_missing = (
        'Authentication failed: workspace missing'
    )
    Authentication_failed__key_missing = 'Authentication failed: key missing'
    Authentication_failed__property__iss___issuer__missing_in_JWT = (
        'Authentication failed: property \'iss\' (issuer) missing in JWT'
    )
    Authentication_failed__property__sub___subject__missing_in_JWT = (
        'Authentication failed: property \'sub\' (subject) missing in JWT'
    )
    Authentication_failed__property__exp___expiration_time__missing_in_JWT = (
        'Authentication failed: property \'exp\' (expiration time) missing in JWT'
    )
    Authentication_failed__invalid__iss___issuer_ = (
        'Authentication failed: invalid \'iss\' (issuer)'
    )
    Authentication_failed__incorrect_signature = (
        'Authentication failed: incorrect signature'
    )
    Authentication_failed = 'Authentication failed'


class TemplatesTemplateIdOutputPostResponse1(BaseModel):
    error: Optional[Error32] = Field(
        None, description='Error description', examples=['Authentication failed']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[401])


class Error33(Enum):
    Your_account_has_exceeded_the_monthly_document_generation_limit_ = (
        'Your account has exceeded the monthly document generation limit.'
    )


class TemplatesTemplateIdOutputPostResponse2(BaseModel):
    error: Optional[Error33] = Field(
        None, description='Error description', examples=['Access not granted']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[403])


class Error34(Enum):
    Entity_not_found = 'Entity not found'
    Resource_not_found = 'Resource not found'
    None_of_the_templates_is_available_for_the_workspace_ = (
        'None of the templates is available for the workspace.'
    )


class TemplatesTemplateIdOutputPostResponse3(BaseModel):
    error: Optional[Error34] = Field(
        None, description='Error description', examples=['Entity not found']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[404])


class Error35(Enum):
    Unable_to_parse_JSON__please_check_formatting = (
        'Unable to parse JSON, please check formatting'
    )
    Required_parameter_missing = 'Required parameter missing'
    Required_parameter_missing__template_definition_not_defined = (
        'Required parameter missing: template definition not defined'
    )
    Required_parameter_missing__template_not_defined = (
        'Required parameter missing: template not defined'
    )


class TemplatesTemplateIdOutputPostResponse4(BaseModel):
    error: Optional[Error35] = Field(
        None, description='Error description', examples=['Incorrect parameter value']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[422])


class TemplatesTemplateIdOutputPostResponse5(BaseModel):
    error: Optional[str] = Field(
        None, description='Error description', examples=['Internal error']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[500])


class WorkspacesWorkspaceIdDeleteResponse(BaseModel):
    response: Optional[Response] = None


class Error36(Enum):
    Authentication_failed__request_expired = 'Authentication failed: request expired'
    Authentication_failed__signature_or_secret_missing = (
        'Authentication failed: signature or secret missing'
    )
    Authentication_failed__workspace_missing = (
        'Authentication failed: workspace missing'
    )
    Authentication_failed__key_missing = 'Authentication failed: key missing'
    Authentication_failed__property__iss___issuer__missing_in_JWT = (
        'Authentication failed: property \'iss\' (issuer) missing in JWT'
    )
    Authentication_failed__property__sub___subject__missing_in_JWT = (
        'Authentication failed: property \'sub\' (subject) missing in JWT'
    )
    Authentication_failed__property__exp___expiration_time__missing_in_JWT = (
        'Authentication failed: property \'exp\' (expiration time) missing in JWT'
    )
    Authentication_failed__invalid__iss___issuer_ = (
        'Authentication failed: invalid \'iss\' (issuer)'
    )
    Authentication_failed__incorrect_signature = (
        'Authentication failed: incorrect signature'
    )
    Authentication_failed = 'Authentication failed'


class WorkspacesWorkspaceIdDeleteResponse1(BaseModel):
    error: Optional[Error36] = Field(
        None, description='Error description', examples=['Authentication failed']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[401])


class Error37(Enum):
    Your_account_has_exceeded_the_monthly_document_generation_limit_ = (
        'Your account has exceeded the monthly document generation limit.'
    )


class WorkspacesWorkspaceIdDeleteResponse2(BaseModel):
    error: Optional[Error37] = Field(
        None, description='Error description', examples=['Access not granted']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[403])


class Error38(Enum):
    Entity_not_found = 'Entity not found'
    Resource_not_found = 'Resource not found'
    None_of_the_templates_is_available_for_the_workspace_ = (
        'None of the templates is available for the workspace.'
    )


class WorkspacesWorkspaceIdDeleteResponse3(BaseModel):
    error: Optional[Error38] = Field(
        None, description='Error description', examples=['Entity not found']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[404])


class Error39(Enum):
    Unable_to_parse_JSON__please_check_formatting = (
        'Unable to parse JSON, please check formatting'
    )
    Required_parameter_missing = 'Required parameter missing'
    Required_parameter_missing__template_definition_not_defined = (
        'Required parameter missing: template definition not defined'
    )
    Required_parameter_missing__template_not_defined = (
        'Required parameter missing: template not defined'
    )


class WorkspacesWorkspaceIdDeleteResponse4(BaseModel):
    error: Optional[Error39] = Field(
        None, description='Error description', examples=['Incorrect parameter value']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[422])


class WorkspacesWorkspaceIdDeleteResponse5(BaseModel):
    error: Optional[str] = Field(
        None, description='Error description', examples=['Internal error']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[500])


class WorkspacesWorkspaceIdGetResponse(BaseModel):
    response: Optional[Workspace] = None


class Error40(Enum):
    Authentication_failed__request_expired = 'Authentication failed: request expired'
    Authentication_failed__signature_or_secret_missing = (
        'Authentication failed: signature or secret missing'
    )
    Authentication_failed__workspace_missing = (
        'Authentication failed: workspace missing'
    )
    Authentication_failed__key_missing = 'Authentication failed: key missing'
    Authentication_failed__property__iss___issuer__missing_in_JWT = (
        'Authentication failed: property \'iss\' (issuer) missing in JWT'
    )
    Authentication_failed__property__sub___subject__missing_in_JWT = (
        'Authentication failed: property \'sub\' (subject) missing in JWT'
    )
    Authentication_failed__property__exp___expiration_time__missing_in_JWT = (
        'Authentication failed: property \'exp\' (expiration time) missing in JWT'
    )
    Authentication_failed__invalid__iss___issuer_ = (
        'Authentication failed: invalid \'iss\' (issuer)'
    )
    Authentication_failed__incorrect_signature = (
        'Authentication failed: incorrect signature'
    )
    Authentication_failed = 'Authentication failed'


class WorkspacesWorkspaceIdGetResponse1(BaseModel):
    error: Optional[Error40] = Field(
        None, description='Error description', examples=['Authentication failed']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[401])


class Error41(Enum):
    Your_account_has_exceeded_the_monthly_document_generation_limit_ = (
        'Your account has exceeded the monthly document generation limit.'
    )


class WorkspacesWorkspaceIdGetResponse2(BaseModel):
    error: Optional[Error41] = Field(
        None, description='Error description', examples=['Access not granted']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[403])


class Error42(Enum):
    Entity_not_found = 'Entity not found'
    Resource_not_found = 'Resource not found'
    None_of_the_templates_is_available_for_the_workspace_ = (
        'None of the templates is available for the workspace.'
    )


class WorkspacesWorkspaceIdGetResponse3(BaseModel):
    error: Optional[Error42] = Field(
        None, description='Error description', examples=['Entity not found']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[404])


class Error43(Enum):
    Unable_to_parse_JSON__please_check_formatting = (
        'Unable to parse JSON, please check formatting'
    )
    Required_parameter_missing = 'Required parameter missing'
    Required_parameter_missing__template_definition_not_defined = (
        'Required parameter missing: template definition not defined'
    )
    Required_parameter_missing__template_not_defined = (
        'Required parameter missing: template not defined'
    )


class WorkspacesWorkspaceIdGetResponse4(BaseModel):
    error: Optional[Error43] = Field(
        None, description='Error description', examples=['Incorrect parameter value']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[422])


class WorkspacesWorkspaceIdGetResponse5(BaseModel):
    error: Optional[str] = Field(
        None, description='Error description', examples=['Internal error']
    )
    status: Optional[int] = Field(None, description='HTTP Error code', examples=[500])


class BatchDatum(BaseModel):
    data: Optional[Data] = None
    template: Optional[int] = Field(None, description='Template id', examples=[52272])


class BatchData(RootModel[List[BatchDatum]]):
    root: List[BatchDatum] = Field(
        ...,
        examples=[
            [
                {'data': {'key': 'value'}, 'template': 52272},
                {'data': {'key2': 'value2'}, 'template': 52273},
            ]
        ],
    )
